# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for Backend

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.profiles.active=test
        working-directory: backend
        env:
          # App Config
          PORT: 8080
          PRIORITY_APPLICATIONS_ACTIVE: false
          FRONTEND_DOMAIN: http://localhost:3000
          BACKEND_DOMAIN: http://localhost:8080
          USER_ACTIVATION_KEY_EXPIRATION_TIME_MS: 3600000
          USER_PASSWORD_RESET_KEY_EXPIRATION_TIME_MS: 3600000
          DISCORD_WEBHOOK=https://discord.com/api/webhooks
          DISCORD_URL: https://discord.com
          DEVPOST_URL: https://devpost.com

          # Security
          BCRYPT_SALT_ROUNDS: 10

          # The following secrets and keys are randomly generated and are not used in production.
          JWT_SECRET: GBbbzRAJ4QJWkdKQqNcB8Sws5TzYcMuMxPkJTPrgrhTvbmFADm95GLHHLNAWkmE4fsmp7y7AhygbP5SH455AtybExf6dWmV3nwxgGbG3qMkGnCTCfw8YsETpsGWj2rPg
          JWT_COOKIE_NAME: refresh_token
          JWT_ACCESS_TOKEN_EXPIRATION_TIME_MS: 900000
          JWT_REFRESH_TOKEN_EXPIRATION_TIME_MS: 2629800000
          VAPID_PUBLIC_KEY: BHQYqLruGFsGLY-k4HynIuRbuLsNh4hCXSDslV1wxf_bNHERubvBLWa-57HV4zO3Ab3_B07ZHav13emWhscDmkQ
          VAPID_PRIVATE_KEY: 7Oju-A7o63PYV2arPlHaP3wtVU9RXzAwcnWlwXqRpeM

          # Mailchimp
          MAILCHIMP_API_KEY: fake_mailchimp_key
          MAILCHIMP_SERVER: us1
          MAILCHIMP_LIST_ID: fake_list_id

          # SendGrid
          SENDGRID_API_KEY: SG.fakekey
          SENDGRID_FROM_EMAIL: noreply@hackbrooklyn.org
          SENDGRID_ACTIVATE_ACCOUNT_TEMPLATE_ID: d-faketemplate
          SENDGRID_RESET_PASSWORD_TEMPLATE_ID: d-faketemplate2

          # AWS
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: fake_access_key
          AWS_SECRET_ACCESS_KEY: fake_secret_access_key
          AWS_S3_BUCKET: hack_brooklyn_plaza_fake_s3_bucket
          AWS_S3_RESUME_DEST: resume
          AWS_SIGNED_URL_DURATION_MS: 3600000

          # Database
          DB_DRIVER_CLASS_NAME: org.postgresql.Driver
          DB_JPA_DATABASE: postgresql
          DB_PLATFORM: postgres
          DB_HOST: jdbc:postgresql://localhost
          DB_PORT: 5432
          DB_NAME: hack_brooklyn_plaza
          DB_USERNAME: fake_user
          DB_PASSWORD: fake_password

          # Redis Database
          REDIS_LOGICAL_DATABASE: 0
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_PASSWORD: fake_password
          REDIS_TIMEOUT: 60000
          REDIS_REFRESH_TOKEN_NAMESPACE: token
